<a href="https://colab.research.google.com/github/Nikosis89/data-sciensce-bootcamp/blob/main/kurs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tablica 1 wymiarowa

In [3]:
import numpy as np
np.__version__

'1.26.4'

tworzenie tablicy i przypisywanie jej do zmiennej

In [10]:
x = np.array ([1.2,2.3,3.1])
print(x)

[1.2 2.3 3.1]


In [11]:
type(x)

numpy.ndarray

In [12]:
x.size

3

In [13]:
x.dtype

dtype('float64')

# Tablica 2 wymiarowa

In [15]:
y= np.array([[1,2,3],[3,4,5]])

In [16]:
print(y)

[[1 2 3]
 [3 4 5]]


In [17]:
y.shape

(2, 3)

In [18]:
y.ndim

2

# Tablice 3d


In [19]:
z = np.array([[[1,2,3],[2,4,3]],
              [[4,4,4],
               [4,2,1]]])

In [22]:
print(z)

[[[1 2 3]
  [2 4 3]]

 [[4 4 4]
  [4 2 1]]]


In [23]:
z.ndim

3

# TypyDanych

In [27]:
a =np.array ([[1,2.3,3],[1,3,2],[1,4,5]],dtype='float')

In [28]:
print(a)

[[1.  2.3 3. ]
 [1.  3.  2. ]
 [1.  4.  5. ]]


In [29]:
a.shape

(3, 3)

In [30]:
b = np.zeros(shape=(10,10),dtype='int')

In [31]:
print(b)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [32]:
b= np.ones(shape=(5,10),dtype='int')

In [33]:
print(b)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [34]:
b = np.full(shape=(3,3),fill_value= 5,dtype='int')

In [35]:
print(b)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [36]:
b =np.arange(6)

In [37]:
print(b)

[0 1 2 3 4 5]


In [38]:
b =np.arange(start=5,stop=11)

In [39]:
print(b)

[ 5  6  7  8  9 10]


In [40]:
b =np.arange(start=0,stop=100,step=10)

In [41]:
print(b)

[ 0 10 20 30 40 50 60 70 80 90]


In [46]:
b =np.linspace(start=1,stop=100,num=10)

In [47]:
print(b)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [53]:
b = np.array([1,2,3,4,5,6,7,8,9])
b= b.reshape((3,-1))

In [54]:
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Operacje na tablicach

In [62]:
x = np.array([[1,2],[1,3]])
y = np.array([[3,2],[5,3]])
z = x*y

In [63]:
print(z)

[[3 4]
 [5 9]]


In [64]:
z = np.add(x,y)

In [65]:
print(z)

[[4 4]
 [6 6]]


mnożenie macieżowe

In [68]:
z = np.dot(x,y)

In [69]:
print(z)

[[13  8]
 [18 11]]


In [70]:
x.dot(y)

array([[13,  8],
       [18, 11]])

In [71]:
y.dot(x)

array([[ 5, 12],
       [ 8, 19]])

In [73]:
y @ x

array([[ 5, 12],
       [ 8, 19]])